<?php
/*
 * Superb_Recommend
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Superb
 * @package    Superb_Recommend
 * @author     Superb <hello@wearesuperb.com>
 * @copyright  Copyright (c) 2015 Superb Media Limited
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<script>
require.config({
    deps: [
        'jquery',
        'jquery/jquery-storageapi',
        'mage/cookies'
    ],
    callback: function($){
        var loadUrl = <?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($this->getTrackLoadUrl()); ?>;
        var trackCookieName = <?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($this->getTrackCookieName()); ?>;
        var trackerFlag = $.mage.cookies.get(trackCookieName);
        if (typeof trackerFlag == 'string' && trackerFlag == 'data-empty') {
            _taq.push(["trackPageview"]);
        } else {
            return $.getJSON(loadUrl, function (_taqRecords) {
                try {
                    var stateKey = 'superb_recommend_taq_key', storage = $.localStorage, flag = 't0';
                    if (typeof storage.get(stateKey) == 'string') {
                        flag = storage.get(stateKey);
                    }
                    for(var index in _taqRecords) {
                        if (index > flag) {
                            _taq.push(_taqRecords[index]);
                            storage.set(stateKey,index);
                        }
                    }
                } catch(e) {};
                _taq.push(["trackPageview"]);
            });
        }
    }
});
</script>
