<?php
/*
 * Superb_Recommend
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Superb
 * @package    Superb_Recommend
 * @author     Superb <hello@wearesuperb.com>
 * @copyright  Copyright (c) 2015 Superb Media Limited
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<div id=<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($this->getRecommendPanelId());?>></div>

<?php $trackerHelper = $this->helper('Superb\Recommend\Helper\Tracker'); ?>
                                                     
<?php if ($trackerHelper->getTrackerVersion() == '35') : ?>
    <script type="text/javascript">
    //<![CDATA[
        var __rtaq = __rtaq || [];
        __rtaq.push(["loadRecommendationPanelToId",<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($this->getRecommendPanelId());?>]);
    //]]>
    </script>
<?php else : ?> 
    <script type="text/javascript">
    //<![CDATA[
        var _taq = _taq || [];
        _taq.push(["loadRecommendationPanelToId",<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($this->getRecommendPanelId());?>]);
    //]]>
    </script>
<?php endif ?>