<?php
/*
 * Superb_Recommend
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0), a
 * copy of which is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   Superb
 * @package    Superb_Recommend
 * @author     Superb <hello@wearesuperb.com>
 * @copyright  Copyright (c) 2015 Superb Media Limited
 * @license    http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>
<?php $helper = $this->helper('Superb\Recommend\Helper\Data'); ?>
<?php $trackerHelper = $this->helper('Superb\Recommend\Helper\Tracker'); ?>
<script>
    (function(){
    var tracker = document.createElement('script'); tracker.type = 'text/javascript'; tracker.async = true;tracker.src = <?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($trackerHelper->getApiJsUrl());?>;
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(tracker, s);
    })();
    var _taq = _taq || [];
    _taq.push(["setAccountId", <?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($helper->getAccountId());?>] ,["setTrackerUrl",<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($trackerHelper->getApiUrl());?>], ["setCurrentCurrencyCode",<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($trackerHelper->getCurrentCurrencyCode());?>], ["setCurrentStoreCode",<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($trackerHelper->getCurrentStoreCode());?>]);
    _taq.push(["trackBeforeRecommendMode",true]);
    <?php $data = $this->getTrackingData();?>
    <?php if (is_array($data)):?><?php foreach ($data as $record): if (is_array($record) && count($record)):?>
    _taq.push(<?php /* @noEscape */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($record);?>);
    <?php endif; endforeach; endif; ?>
</script>
<?php echo $this->getChildHtml('recommend_tracker');?>